#!/usr/bin/env zsh

() {
	local file
	for file in $(git diff --name-only --staged); do
		local file_ext="${file##*.}"

		if [[ "$file_ext" == "rs" ]]; then
			cargo +nightly fmt -- "$file"
			git add "$file"
		fi
	done

	cargo clippy --fix --all-targets --workspace --allow-staged --allow-dirty --color='always'
	cargo test --workspace --color='always'
}
