#!/usr/bin/env zsh

for file in $(cargo +nightly fmt -- --emit json | jq -r '.[].name'); do
	cargo +nightly fmt -- $file
	git add $file
done

cargo clippy --fix --all-targets --workspace --allow-staged --allow-dirty
cargo test --workspace
