[package]
name = "typesitter"
version = "0.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
log = "0.4.0"
env_logger = "0.8.4"
clap = { version = "3.0.5", features = ["derive"] }
anyhow = "1.0.52"
nom = "7.1.0"
