---
name: LLVM installer
description: Install LLVM

inputs:
  llvm-version:
    description: "The version of LLVM to install"
    required: false
    default: "14"

runs:
  using: composite
  steps:
    - name: Install LLVM
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install --yes software-properties-common lsb-release
        cd "$(mktemp -d)"
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh ${{ inputs.llvm-version }}
        echo "LLVM_SYS_${{ inputs.llvm-version }}0_PREFIX=/usr/lib/llvm-${{ inputs.llvm-version }}" >> $GITHUB_ENV
