name: Toolchain
description: Rust toolchain setup

runs:
  using: composite
  steps:
    - name: Install LLVM
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install --yes software-properties-common lsb-release
        cd /tmp
        wget https://apt.llvm.org/llvm.sh
        chmod +x llvm.sh
        sudo ./llvm.sh 14
        echo "LLVM_SYS_140_PREFIX=/usr/lib/llvm-14" >> $GITHUB_ENV
