on:
  push:
    paths:
      - crates/frontends/web/**
name: Publish on Netlify

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Publish
        uses: netlify/actions/build@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_BASE: crates/frontends/web/
          NETLIFY_CMD: |
            curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh && \
            yarn && \
            yarn build:wasm && \
            yarn build
          NETLIFY_DIR: crates/frontends/web/dist/
