name: GitHub Pages Publish

on:
  push:
    paths:
      - demo/**
      - .github/workflows/publish-demo.yaml
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: demo/yarn.lock
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build
        working-directory: demo
        run: |
          yarn install --immutable
          yarn build:wasm
          yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: demo
          folder: demo/dist/
