name: GitHub Pages Publish

on:
  push:
    paths:
      - demo/**
      - .github/workflows/publish-demo.yaml
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 6
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: pnpm
          cache-dependency-path: demo/pnpm-lock.yaml
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      - name: Build WASM Binary
        run: sh crates/utils/js_bind/build-demo.sh
      - name: Install deps
        working-directory: demo
        run: pnpm install --frozen-lockfile
      - name: Build
        env:
          NODE_ENV: production
        working-directory: demo
        run: pnpm run build:prod
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: demo
          folder: demo/dist/
